const books=[
{id:'atomic-habits',title:'Atomic Habits',author:'James Clear',genre:'Self Help',year:2018,pages:320,desc:'A practical guide to building better habits, breaking bad ones, and making small changes that create remarkable results.'},
{id:'midnight-library',title:'The Midnight Library',author:'Matt Haig',genre:'Fiction',year:2020,pages:304,desc:'A thoughtful fiction story exploring choices, possibilities and the many lives a person might imagine.'},
{id:'sapiens',title:'Sapiens',author:'Yuval Noah Harari',genre:'History',year:2011,pages:498,desc:'A broad journey through human history, from early humans to the modern world.'},
{id:'dune',title:'Dune',author:'Frank Herbert',genre:'Sci-Fi',year:1965,pages:688,desc:'An epic science-fiction adventure set on the desert planet Arrakis.'},
{id:'1984',title:'1984',author:'George Orwell',genre:'Dystopian',year:1949,pages:328,desc:'A classic dystopian novel about surveillance, truth and individual freedom.'},
{id:'hobbit',title:'The Hobbit',author:'J.R.R. Tolkien',genre:'Fantasy',year:1937,pages:310,desc:'A fantasy adventure following Bilbo Baggins on an unexpected journey.'},
{id:'rich-dad',title:'Rich Dad Poor Dad',author:'Robert T. Kiyosaki',genre:'Finance',year:1997,pages:336,desc:'A popular introduction to personal finance and financial thinking.'},
{id:'clean-code',title:'Clean Code',author:'Robert C. Martin',genre:'Programming',year:2008,pages:464,desc:'A practical programming book about writing readable and maintainable code.'},
{id:'thinking',title:'Thinking, Fast and Slow',author:'Daniel Kahneman',genre:'Psychology',year:2011,pages:499,desc:'An exploration of the two systems that shape human judgment and decisions.'},
{id:'educated',title:'Educated',author:'Tara Westover',genre:'Memoir',year:2018,pages:352,desc:'A memoir about education, identity and the journey toward a wider understanding of the world.'},
{id:'martian',title:'The Martian',author:'Andy Weir',genre:'Sci-Fi',year:2011,pages:369,desc:'A fast-paced survival story about an astronaut stranded on Mars.'},
{id:'mockingbird',title:'To Kill a Mockingbird',author:'Harper Lee',genre:'Classic',year:1960,pages:336,desc:'A coming-of-age classic centered on justice, empathy and community.'}
];
function cover(b){return `<div class="cover"><div><h3>${b.title}</h3><p>${b.author}</p></div></div>`}
function card(b){return `<article class="card"><a href="book.html?id=${b.id}">${cover(b)}<h3>${b.title}</h3><div class="author">${b.author}</div><span class="tag">${b.genre}</span></a></article>`}
const featured=document.getElementById('featured');if(featured)featured.innerHTML=books.slice(0,4).map(card).join('');
const bookGrid=document.getElementById('books');if(bookGrid){const q=document.getElementById('q'),sort=document.getElementById('sort'),chips=document.getElementById('chips'),empty=document.getElementById('empty');let genre='All';['All',...new Set(books.map(b=>b.genre))].forEach(g=>{const x=document.createElement('button');x.className='chip'+(g==='All'?' active':'');x.textContent=g;x.onclick=()=>{genre=g;document.querySelectorAll('.chip').forEach(c=>c.classList.remove('active'));x.classList.add('active');render()};chips.appendChild(x)});function render(){let list=[...books],s=(q.value||'').toLowerCase();if(s)list=list.filter(b=>(b.title+' '+b.author+' '+b.genre).toLowerCase().includes(s));if(genre!=='All')list=list.filter(b=>b.genre===genre);if(sort.value==='az')list.sort((a,b)=>a.title.localeCompare(b.title));if(sort.value==='author')list.sort((a,b)=>a.author.localeCompare(b.author));bookGrid.innerHTML=list.map(card).join('');empty.classList.toggle('hidden',list.length>0)}document.getElementById('searchForm').onsubmit=e=>{e.preventDefault();render()};q.oninput=render;sort.onchange=render;const initial=new URLSearchParams(location.search).get('q');if(initial)q.value=initial;render()}
const cats=document.getElementById('categories');if(cats){const names=[...new Set(books.map(b=>b.genre))];cats.innerHTML=names.map((g,i)=>`<article class="category" onclick="location.href='books.html?q=${encodeURIComponent(g)}'"><div class="category-icon">${['📚','◉','✦','◆','●','★'][i%6]}</div><h3>${g}</h3><p>${books.filter(b=>b.genre===g).length} book(s) in this collection</p></article>`).join('')}
const details=document.getElementById('details');if(details){const id=new URLSearchParams(location.search).get('id')||books[0].id,b=books.find(x=>x.id===id)||books[0];details.innerHTML=`<a href="books.html">← Back to Books</a><div class="details" style="margin-top:22px"><div>${cover(b)}</div><div><small>${b.genre.toUpperCase()}</small><h1>${b.title}</h1><div class="author">${b.author}</div><div class="rating">★★★★★ <span style="color:#71808e;font-size:12px">(4.8) · Reader favorite</span></div><p>${b.desc}</p><p style="margin-top:12px"><button class="btn" onclick="alert('Reading mode demo')">Read More</button><button class="btn outline" onclick="alert('Added to wishlist (demo)')">♡ Wishlist</button></p><div class="stats"><div class="stat"><small>AUTHOR</small><b>${b.author}</b></div><div class="stat"><small>PUBLISHED</small><b>${b.year}</b></div><div class="stat"><small>PAGES</small><b>${b.pages}</b></div></div></div></div>`}
const form=document.getElementById('contactForm');if(form)form.onsubmit=e=>{e.preventDefault();document.getElementById('sent').classList.remove('hidden');form.reset()}
